name: core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  built_value: ^8.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  built_value_generator: ^8.8.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
